name: Trigger VerixAI Automation Tests

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - staging
      - prod
  workflow_dispatch: 

env:
  TEST_ENV: dev

jobs:
  trigger-tests:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger VerixAI Automation Test
        id: trigger-test
        shell: pwsh
        env:
          VERIXAI_API_DOMAIN: ${{ secrets.VERIXAI_API_DOMAIN }}
          VERIXAI_API_TOKEN: ${{ secrets.VERIXAI_API_TOKEN }}
        run: |
          $COMMIT_MSG = git log -1 --pretty=format:"%s"
          $COMMIT_AUTHOR = git log -1 --pretty=format:"%an"

          $payload = @{
            case_details = @{
              title = "Sample Test Case"
              plaintiff_name = "John Doe"
              medical_provider = "Test Hospital"
              description = "This is a sample test case for VerixAI automation"
            }
          } | ConvertTo-Json -Depth 10

          $payload | Out-File -FilePath test_payload.json

          $headers = @{
            "Content-Type" = "application/json"
          }

          if ($env:VERIXAI_API_TOKEN -and $env:VERIXAI_API_TOKEN -ne "") {
            $headers["Authorization"] = "Bearer $env:VERIXAI_API_TOKEN"
          }

          $url = "https://$env:VERIXAI_API_DOMAIN/api/run-test?env=${{ env.TEST_ENV }}"
          Write-Output "Triggering API at: $url"

          try {
            $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $payload

            Write-Output "Response from API:"
            $response | ConvertTo-Json

            $TEST_ID = $response.test_id
            "test_id=$TEST_ID" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            Write-Output "Triggered test with ID: $TEST_ID"

            if (-not $TEST_ID) {
              Write-Output "Failed to trigger test. API response: $($response | ConvertTo-Json)"
              exit 1
            }
          }
          catch {
            Write-Output "Error calling API: $_"
            Write-Output "Status Code: $($_.Exception.Response.StatusCode.value__)"
            Write-Output "Response: $($_.ErrorDetails.Message)"
            exit 1
          }
