name: Trigger VerixAI Automation Tests

on:
  pull_request:
    types: [closed]
    branches:
      - master # Only trigger when PRs are merged to dev branch
  workflow_dispatch: # Allows manual triggering from GitHub UI

env:
  VERIXAI_API_URL: https://dev-verixai-automation.cormetrix.com
  TEST_ENV: dev

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Trigger VerixAI Automation Test
        id: trigger-test
        run: |
          # Get commit info
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")

          # Create payload with only case details
          cat > test_payload.json << EOF
          {
            "case_details": {
              "title": "Merged PR - ${COMMIT_AUTHOR}",
              "plaintiff_name": "GitHub PR-${{ github.run_id }}",
              "medical_provider": "Test Hospital",
              "description": "Automated test triggered by merged PR: ${COMMIT_MSG}"
            }
          }
          EOF

          # Prepare curl authorization header if token is present
          if [ -n "${{ secrets.VERIXAI_API_TOKEN }}" ]; then
            export AUTH_HEADER="-H \"Authorization: Bearer ${{ secrets.VERIXAI_API_TOKEN }}\""
          fi

          # Trigger test
          RESPONSE=$(eval curl -s -X POST \
            -H "Content-Type: application/json" \
            $AUTH_HEADER \
            -d @test_payload.json \
            "${{ env.VERIXAI_API_URL }}/api/run-test?env=${{ env.TEST_ENV }}")

          echo "Response from API: $RESPONSE" # Add this to see the full response

          # Get test ID
          TEST_ID=$(echo $RESPONSE | jq -r '.test_id')
          echo "test_id=$TEST_ID" >> $GITHUB_OUTPUT
          echo "Triggered test with ID: $TEST_ID"

          # Check if successful
          if [ -z "$TEST_ID" ] || [ "$TEST_ID" == "null" ]; then
            echo "Failed to trigger test. API response: $RESPONSE"
            exit 1
          fi

      # Follow-up steps remain unchanged
